//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 04/04/2015 14:22:44
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace MfinderContext
{

    [DatabaseAttribute(Name = "mfinder")]
    [ProviderAttribute(typeof(Devart.Data.MySql.Linq.Provider.MySqlDataProvider))]
    public partial class MfinderDataContext : Devart.Data.Linq.DataContext
    {
        public static CompiledQueryCache compiledQueryCache = CompiledQueryCache.RegisterDataContext(typeof(MfinderDataContext));
        private static MappingSource mappingSource = new Devart.Data.Linq.Mapping.AttributeMappingSource();

        #region Extensibility Method Definitions
    
        partial void OnCreated();
        partial void OnSubmitError(Devart.Data.Linq.SubmitErrorEventArgs args);
        partial void InsertAction(Action instance);
        partial void UpdateAction(Action instance);
        partial void DeleteAction(Action instance);
        partial void InsertDpto(Dpto instance);
        partial void UpdateDpto(Dpto instance);
        partial void DeleteDpto(Dpto instance);
        partial void InsertMachine(Machine instance);
        partial void UpdateMachine(Machine instance);
        partial void DeleteMachine(Machine instance);
        partial void InsertRole(Role instance);
        partial void UpdateRole(Role instance);
        partial void DeleteRole(Role instance);
        partial void InsertUser(User instance);
        partial void UpdateUser(User instance);
        partial void DeleteUser(User instance);

        #endregion

        public MfinderDataContext() :
        base(GetConnectionString("MfinderDataContextConnectionString"), mappingSource)
        {
            OnCreated();
        }

        public MfinderDataContext(MappingSource mappingSource) :
        base(GetConnectionString("MfinderDataContextConnectionString"), mappingSource)
        {
            OnCreated();
        }

        private static string GetConnectionString(string connectionStringName)
        {
            System.Configuration.ConnectionStringSettings connectionStringSettings = System.Configuration.ConfigurationManager.ConnectionStrings[connectionStringName];
            if (connectionStringSettings == null)
                throw new InvalidOperationException("Connection string \"" + connectionStringName +"\" could not be found in the configuration file.");
            return connectionStringSettings.ConnectionString;
        }

        public MfinderDataContext(string connection) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public MfinderDataContext(System.Data.IDbConnection connection) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public MfinderDataContext(string connection, MappingSource mappingSource) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public MfinderDataContext(System.Data.IDbConnection connection, MappingSource mappingSource) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public Devart.Data.Linq.Table<Action> Actions
        {
            get
            {
                return this.GetTable<Action>();
            }
        }

        public Devart.Data.Linq.Table<Dpto> Dptos
        {
            get
            {
                return this.GetTable<Dpto>();
            }
        }

        public Devart.Data.Linq.Table<History> Histories
        {
            get
            {
                return this.GetTable<History>();
            }
        }

        public Devart.Data.Linq.Table<Location> Locations
        {
            get
            {
                return this.GetTable<Location>();
            }
        }

        public Devart.Data.Linq.Table<Machine> Machines
        {
            get
            {
                return this.GetTable<Machine>();
            }
        }

        public Devart.Data.Linq.Table<Role> Roles
        {
            get
            {
                return this.GetTable<Role>();
            }
        }

        public Devart.Data.Linq.Table<User> Users
        {
            get
            {
                return this.GetTable<User>();
            }
        }
    }
}

namespace MfinderContext
{

    /// <summary>
    /// There are no comments for MfinderContext.Action in the schema.
    /// </summary>
    [Table(Name = @"mfinder.`action`")]
    public partial class Action : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _Id;

        private string _Name;
        #pragma warning restore 0649
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        #endregion

        public Action()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        [Column(Name = @"id", Storage = "_Id", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "INT(11) NOT NULL AUTO_INCREMENT", IsDbGenerated = true, IsPrimaryKey = true)]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging();
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        [Column(Name = @"name", Storage = "_Name", DbType = "VARCHAR(45) NULL", UpdateCheck = UpdateCheck.Never)]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                if (this._Name != value)
                {
                    this.OnNameChanging(value);
                    this.SendPropertyChanging();
                    this._Name = value;
                    this.SendPropertyChanged("Name");
                    this.OnNameChanged();
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    /// <summary>
    /// There are no comments for MfinderContext.Dpto in the schema.
    /// </summary>
    [Table(Name = @"mfinder.dpto")]
    public partial class Dpto : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _Id;

        private string _Name;
        #pragma warning restore 0649

        private EntitySet<User> _Users;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        #endregion

        public Dpto()
        {
            this._Users = new EntitySet<User>(new Action<User>(this.attach_Users), new Action<User>(this.detach_Users));
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        [Column(Name = @"id", Storage = "_Id", CanBeNull = false, DbType = "INT(11) NOT NULL", IsPrimaryKey = true)]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging();
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        [Column(Name = @"name", Storage = "_Name", CanBeNull = false, DbType = "VARCHAR(45) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                if (this._Name != value)
                {
                    this.OnNameChanging(value);
                    this.SendPropertyChanging();
                    this._Name = value;
                    this.SendPropertyChanged("Name");
                    this.OnNameChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Dpto_User", Storage="_Users", ThisKey="Id", OtherKey="DptoFk", DeleteRule="NO ACTION")]
        public EntitySet<User> Users
        {
            get
            {
                return this._Users;
            }
            set
            {
                this._Users.Assign(value);
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }

        private void attach_Users(User entity)
        {
            this.SendPropertyChanging("Users");
            entity.Dpto = this;
        }
    
        private void detach_Users(User entity)
        {
            this.SendPropertyChanging("Users");
            entity.Dpto = null;
        }
    }

    /// <summary>
    /// There are no comments for MfinderContext.History in the schema.
    /// </summary>
    [Table(Name = @"mfinder.history")]
    public partial class History
    {
        #pragma warning disable 0649

        private int _ActionFk;

        private System.Nullable<int> _UserFk;

        private System.Nullable<int> _MachineFk;

        private System.Nullable<int> _DptoFk;

        private string _Comment;

        private System.Nullable<System.DateTime> _ActionDate;

        private System.Nullable<int> _TechnicalFk;
        #pragma warning restore 0649
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnActionFkChanging(int value);
        partial void OnActionFkChanged();
        partial void OnUserFkChanging(System.Nullable<int> value);
        partial void OnUserFkChanged();
        partial void OnMachineFkChanging(System.Nullable<int> value);
        partial void OnMachineFkChanged();
        partial void OnDptoFkChanging(System.Nullable<int> value);
        partial void OnDptoFkChanged();
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        partial void OnActionDateChanging(System.Nullable<System.DateTime> value);
        partial void OnActionDateChanged();
        partial void OnTechnicalFkChanging(System.Nullable<int> value);
        partial void OnTechnicalFkChanged();
        #endregion

        public History()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for ActionFk in the schema.
        /// </summary>
        [Column(Name = @"action_fk", Storage = "_ActionFk", CanBeNull = false, DbType = "INT(11) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public int ActionFk
        {
            get
            {
                return this._ActionFk;
            }
            set
            {
                if (this._ActionFk != value)
                {
                    this._ActionFk = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for UserFk in the schema.
        /// </summary>
        [Column(Name = @"user_fk", Storage = "_UserFk", DbType = "INT(11) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<int> UserFk
        {
            get
            {
                return this._UserFk;
            }
            set
            {
                if (this._UserFk != value)
                {
                    this._UserFk = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for MachineFk in the schema.
        /// </summary>
        [Column(Name = @"machine_fk", Storage = "_MachineFk", DbType = "INT(11) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<int> MachineFk
        {
            get
            {
                return this._MachineFk;
            }
            set
            {
                if (this._MachineFk != value)
                {
                    this._MachineFk = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for DptoFk in the schema.
        /// </summary>
        [Column(Name = @"dpto_fk", Storage = "_DptoFk", DbType = "INT(11) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<int> DptoFk
        {
            get
            {
                return this._DptoFk;
            }
            set
            {
                if (this._DptoFk != value)
                {
                    this._DptoFk = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Comment in the schema.
        /// </summary>
        [Column(Name = @"`comment`", Storage = "_Comment", DbType = "VARCHAR(255) NULL", UpdateCheck = UpdateCheck.Never)]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                if (this._Comment != value)
                {
                    this._Comment = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for ActionDate in the schema.
        /// </summary>
        [Column(Name = @"actionDate", Storage = "_ActionDate", DbType = "DATETIME NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> ActionDate
        {
            get
            {
                return this._ActionDate;
            }
            set
            {
                if (this._ActionDate != value)
                {
                    this._ActionDate = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for TechnicalFk in the schema.
        /// </summary>
        [Column(Name = @"technical_fk", Storage = "_TechnicalFk", DbType = "INT(11) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<int> TechnicalFk
        {
            get
            {
                return this._TechnicalFk;
            }
            set
            {
                if (this._TechnicalFk != value)
                {
                    this._TechnicalFk = value;
                }
            }
        }
    }

    /// <summary>
    /// There are no comments for MfinderContext.Location in the schema.
    /// </summary>
    [Table(Name = @"mfinder.location")]
    public partial class Location
    {
        #pragma warning disable 0649

        private System.Nullable<int> _UserFk;

        private System.Nullable<int> _DptoFk;

        private int _MachineFk;

        private string _Comment;

        private System.Nullable<int> _TechnicalFk;
        #pragma warning restore 0649
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnUserFkChanging(System.Nullable<int> value);
        partial void OnUserFkChanged();
        partial void OnDptoFkChanging(System.Nullable<int> value);
        partial void OnDptoFkChanged();
        partial void OnMachineFkChanging(int value);
        partial void OnMachineFkChanged();
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        partial void OnTechnicalFkChanging(System.Nullable<int> value);
        partial void OnTechnicalFkChanged();
        #endregion

        public Location()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for UserFk in the schema.
        /// </summary>
        [Column(Name = @"user_fk", Storage = "_UserFk", DbType = "INT(11) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<int> UserFk
        {
            get
            {
                return this._UserFk;
            }
            set
            {
                if (this._UserFk != value)
                {
                    this._UserFk = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for DptoFk in the schema.
        /// </summary>
        [Column(Name = @"dpto_fk", Storage = "_DptoFk", DbType = "INT(11) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<int> DptoFk
        {
            get
            {
                return this._DptoFk;
            }
            set
            {
                if (this._DptoFk != value)
                {
                    this._DptoFk = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for MachineFk in the schema.
        /// </summary>
        [Column(Name = @"machine_fk", Storage = "_MachineFk", CanBeNull = false, DbType = "INT(11) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public int MachineFk
        {
            get
            {
                return this._MachineFk;
            }
            set
            {
                if (this._MachineFk != value)
                {
                    this._MachineFk = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Comment in the schema.
        /// </summary>
        [Column(Name = @"`comment`", Storage = "_Comment", DbType = "VARCHAR(255) NULL", UpdateCheck = UpdateCheck.Never)]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                if (this._Comment != value)
                {
                    this._Comment = value;
                }
            }
        }

    
        /// <summary>
        /// There are no comments for TechnicalFk in the schema.
        /// </summary>
        [Column(Name = @"technical_fk", Storage = "_TechnicalFk", DbType = "INT(11) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<int> TechnicalFk
        {
            get
            {
                return this._TechnicalFk;
            }
            set
            {
                if (this._TechnicalFk != value)
                {
                    this._TechnicalFk = value;
                }
            }
        }
    }

    /// <summary>
    /// There are no comments for MfinderContext.Machine in the schema.
    /// </summary>
    [Table(Name = @"mfinder.machine")]
    public partial class Machine : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _Id;

        private string _Model;

        private string _Serialnumber;

        private string _Name;

        private System.Nullable<System.DateTime> _AquisitionDate;

        private System.Nullable<System.DateTime> _WarrantyExpirationDate;
        #pragma warning restore 0649
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnModelChanging(string value);
        partial void OnModelChanged();
        partial void OnSerialnumberChanging(string value);
        partial void OnSerialnumberChanged();
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        partial void OnAquisitionDateChanging(System.Nullable<System.DateTime> value);
        partial void OnAquisitionDateChanged();
        partial void OnWarrantyExpirationDateChanging(System.Nullable<System.DateTime> value);
        partial void OnWarrantyExpirationDateChanged();
        #endregion

        public Machine()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        [Column(Name = @"id", Storage = "_Id", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "INT(11) NOT NULL AUTO_INCREMENT", IsDbGenerated = true, IsPrimaryKey = true)]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging();
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Model in the schema.
        /// </summary>
        [Column(Name = @"model", Storage = "_Model", DbType = "VARCHAR(45) NULL", UpdateCheck = UpdateCheck.Never)]
        public string Model
        {
            get
            {
                return this._Model;
            }
            set
            {
                if (this._Model != value)
                {
                    this.OnModelChanging(value);
                    this.SendPropertyChanging();
                    this._Model = value;
                    this.SendPropertyChanged("Model");
                    this.OnModelChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Serialnumber in the schema.
        /// </summary>
        [Column(Name = @"serialnumber", Storage = "_Serialnumber", CanBeNull = false, DbType = "VARCHAR(45) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Serialnumber
        {
            get
            {
                return this._Serialnumber;
            }
            set
            {
                if (this._Serialnumber != value)
                {
                    this.OnSerialnumberChanging(value);
                    this.SendPropertyChanging();
                    this._Serialnumber = value;
                    this.SendPropertyChanged("Serialnumber");
                    this.OnSerialnumberChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        [Column(Name = @"name", Storage = "_Name", DbType = "VARCHAR(45) NULL", UpdateCheck = UpdateCheck.Never)]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                if (this._Name != value)
                {
                    this.OnNameChanging(value);
                    this.SendPropertyChanging();
                    this._Name = value;
                    this.SendPropertyChanged("Name");
                    this.OnNameChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for AquisitionDate in the schema.
        /// </summary>
        [Column(Name = @"aquisitionDate", Storage = "_AquisitionDate", DbType = "DATETIME NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> AquisitionDate
        {
            get
            {
                return this._AquisitionDate;
            }
            set
            {
                if (this._AquisitionDate != value)
                {
                    this.OnAquisitionDateChanging(value);
                    this.SendPropertyChanging();
                    this._AquisitionDate = value;
                    this.SendPropertyChanged("AquisitionDate");
                    this.OnAquisitionDateChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for WarrantyExpirationDate in the schema.
        /// </summary>
        [Column(Name = @"warrantyExpirationDate", Storage = "_WarrantyExpirationDate", DbType = "DATETIME NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> WarrantyExpirationDate
        {
            get
            {
                return this._WarrantyExpirationDate;
            }
            set
            {
                if (this._WarrantyExpirationDate != value)
                {
                    this.OnWarrantyExpirationDateChanging(value);
                    this.SendPropertyChanging();
                    this._WarrantyExpirationDate = value;
                    this.SendPropertyChanged("WarrantyExpirationDate");
                    this.OnWarrantyExpirationDateChanged();
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    /// <summary>
    /// There are no comments for MfinderContext.Role in the schema.
    /// </summary>
    [Table(Name = @"mfinder.role")]
    public partial class Role : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _Id;

        private string _Name;
        #pragma warning restore 0649

        private EntitySet<User> _Users;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        #endregion

        public Role()
        {
            this._Users = new EntitySet<User>(new Action<User>(this.attach_Users), new Action<User>(this.detach_Users));
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        [Column(Name = @"id", Storage = "_Id", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "INT(11) NOT NULL AUTO_INCREMENT", IsDbGenerated = true, IsPrimaryKey = true)]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging();
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        [Column(Name = @"name", Storage = "_Name", CanBeNull = false, DbType = "VARCHAR(45) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                if (this._Name != value)
                {
                    this.OnNameChanging(value);
                    this.SendPropertyChanging();
                    this._Name = value;
                    this.SendPropertyChanged("Name");
                    this.OnNameChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Role_User", Storage="_Users", ThisKey="Id", OtherKey="RoleFk", DeleteRule="NO ACTION")]
        public EntitySet<User> Users
        {
            get
            {
                return this._Users;
            }
            set
            {
                this._Users.Assign(value);
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }

        private void attach_Users(User entity)
        {
            this.SendPropertyChanging("Users");
            entity.Role = this;
        }
    
        private void detach_Users(User entity)
        {
            this.SendPropertyChanging("Users");
            entity.Role = null;
        }
    }

    /// <summary>
    /// There are no comments for MfinderContext.User in the schema.
    /// </summary>
    [Table(Name = @"mfinder.user")]
    public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _Id;

        private string _Name;

        private string _Ramal;

        private int _RoleFk;

        private System.Nullable<int> _DptoFk;
        #pragma warning restore 0649

        private EntityRef<Dpto> _Dpto;

        private EntityRef<Role> _Role;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        partial void OnRamalChanging(string value);
        partial void OnRamalChanged();
        partial void OnRoleFkChanging(int value);
        partial void OnRoleFkChanged();
        partial void OnDptoFkChanging(System.Nullable<int> value);
        partial void OnDptoFkChanged();
        #endregion

        public User()
        {
            this._Dpto  = default(EntityRef<Dpto>);
            this._Role  = default(EntityRef<Role>);
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        [Column(Name = @"id", Storage = "_Id", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "INT(11) NOT NULL AUTO_INCREMENT", IsDbGenerated = true, IsPrimaryKey = true)]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging();
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        [Column(Name = @"name", Storage = "_Name", DbType = "VARCHAR(45) NULL", UpdateCheck = UpdateCheck.Never)]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                if (this._Name != value)
                {
                    this.OnNameChanging(value);
                    this.SendPropertyChanging();
                    this._Name = value;
                    this.SendPropertyChanged("Name");
                    this.OnNameChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Ramal in the schema.
        /// </summary>
        [Column(Name = @"ramal", Storage = "_Ramal", DbType = "VARCHAR(45) NULL", UpdateCheck = UpdateCheck.Never)]
        public string Ramal
        {
            get
            {
                return this._Ramal;
            }
            set
            {
                if (this._Ramal != value)
                {
                    this.OnRamalChanging(value);
                    this.SendPropertyChanging();
                    this._Ramal = value;
                    this.SendPropertyChanged("Ramal");
                    this.OnRamalChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for RoleFk in the schema.
        /// </summary>
        [Column(Name = @"role_fk", Storage = "_RoleFk", CanBeNull = false, DbType = "INT(11) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public int RoleFk
        {
            get
            {
                return this._RoleFk;
            }
            set
            {
                if (this._RoleFk != value)
                {
                    if (this._Role.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnRoleFkChanging(value);
                    this.SendPropertyChanging();
                    this._RoleFk = value;
                    this.SendPropertyChanged("RoleFk");
                    this.OnRoleFkChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for DptoFk in the schema.
        /// </summary>
        [Column(Name = @"dpto_fk", Storage = "_DptoFk", DbType = "INT(11) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<int> DptoFk
        {
            get
            {
                return this._DptoFk;
            }
            set
            {
                if (this._DptoFk != value)
                {
                    if (this._Dpto.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnDptoFkChanging(value);
                    this.SendPropertyChanging();
                    this._DptoFk = value;
                    this.SendPropertyChanged("DptoFk");
                    this.OnDptoFkChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Dpto in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Dpto_User", Storage="_Dpto", ThisKey="DptoFk", OtherKey="Id", IsForeignKey=true)]
        public Dpto Dpto
        {
            get
            {
                return this._Dpto.Entity;
            }
            set
            {
                Dpto previousValue = this._Dpto.Entity;
                if ((previousValue != value) || (this._Dpto.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._Dpto.Entity = null;
                        previousValue.Users.Remove(this);
                    }
                    this._Dpto.Entity = value;
                    if (value != null)
                    {
                        this._DptoFk = value.Id;
                        value.Users.Add(this);
                    }
                    else
                    {
                        this._DptoFk = default(System.Nullable<int>);
                    }
                    this.SendPropertyChanged("Dpto");
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Role in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Role_User", Storage="_Role", ThisKey="RoleFk", OtherKey="Id", IsForeignKey=true)]
        public Role Role
        {
            get
            {
                return this._Role.Entity;
            }
            set
            {
                Role previousValue = this._Role.Entity;
                if ((previousValue != value) || (this._Role.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._Role.Entity = null;
                        previousValue.Users.Remove(this);
                    }
                    this._Role.Entity = value;
                    if (value != null)
                    {
                        this._RoleFk = value.Id;
                        value.Users.Add(this);
                    }
                    else
                    {
                        this._RoleFk = default(int);
                    }
                    this.SendPropertyChanged("Role");
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
